image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components
before_script:
  - npm install -g firebase-tools
  - npm install

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm run build-prod
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - stage
  script:
    - npm run build-stage
    - firebase use --token $FIREBASE_DEPLOY_KEY stage
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
