image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components
  before_script:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install -g @angular/cli@8.0.0-rc.2
    - npm install --no-optional

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - ng build --prod
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - stage
  script:
    - ng build --configuration=stage
    - firebase use --token $FIREBASE_DEPLOY_KEY stage
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
